### ISSUE TITLE
[Bug]: Navbar width is not correct

### ISSUE THREAD

**Issue by iamjunaidjutt** [iamjunaidjutt/iamjunaidjutt-portfolio#1]
**Describe the bug**
The navbar width is not correct from the left side. It has some space between the navbar and sidebar that is visible on the colored background. The behavior is also not good on mobile devices.

**To Reproduce**
1. Go to the main page of the website
2. Scroll down to the blue background
3. See error

**Expected behavior**
There would be no space between the navbar and the sidebar. These both will look combined with each other. On small devices, it will expand to full width.

**Screenshots**
![Screenshot from 2023-10-27 10-17-53](https://github.com/iamjunaidjutt/iamjunaidjutt-portfolio/assets/84816593/968eefd0-8669-4e0f-9dfa-6e1c9e48bb82)

**Comment by Virtual4087** [comment]
I can fix it. Can you assign me?
